### ISSUE TITLE
Need to distinguish blog posts more clearly

### ISSUE THREAD

**Issue by danielnemenyi** [danielnemenyi/mad-spinning-top#10]
On the main blog roll page, it's not very clear where one posts ends and another begins, and the header hierarchy isn't right (h3's instead of h2's).

**Comment by toupiefolle** [comment]
I confess I'm not sure which page or part to look at.
Relatedly, is it possible for the list of blogs at the top to be ordered so the most recent is first? 

screen shot here

<img width="1440" alt="Screenshot 2022-05-31 at 11 54 19" src="https://user-images.githubusercontent.com/106591765/171157796-24ad620c-548d-4070-b943-c45eb0eeb098.png">

**Comment by danielnemenyi** [comment]
> list of blogs at the top to be ordered so the most recent is first

Done: 62e2acc

**Comment by danielnemenyi** [comment]
Actually, @toupiefolle , do you find the numbers on the side of the blog post index useful, or would you rather I stripped them?  

![image](https://user-images.githubusercontent.com/8701448/172153944-61e449f6-1ce9-4a5b-9498-4ef3aede3b11.png)

**Comment by danielnemenyi** [comment]
I've spaced out blog posts a bit more, and increased their title font, so hopefully the posts should look more distinct now.
