### ISSUE TITLE
Names on about page are not backlinking

### ISSUE THREAD

**Issue by danielnemenyi** [danielnemenyi/mad-spinning-top#11]
**Describe the bug**
Patrick, Susana and Daniel's name on the about page are not linking, because the page doesn't live within the _notes directory.

Either about.md should be moved to the _notes directory or the linking algorithm should be made to take a list of directories (which could include _posts, so that we can get the benefits of using Jekyll's blog mechanisms, such as snippets).

**To reproduce**
1. Go to https://mad-spinning-top.netlify.app/about
2. Hover over Dr. Susana Caló

**Expected behavior**
Should link to Dr. Susana Caló's backlinks.

**Screenshots**
![image](https://user-images.githubusercontent.com/8701448/170250921-20ced076-4a2e-4664-8aee-6fe4a9cffd70.png)

**Comment by toupiefolle** [comment]
Sorry Daniel, not sure if you are asking something here ? Is there something I can do or decide upon to resolve the bug?
P

**Comment by danielnemenyi** [comment]
No, sorry Patrick for the confusion, this is a note to self for something I need to look into.
