### ISSUE TITLE
Blog post update?  25 February 2022

### ISSUE THREAD

**Issue by danielnemenyi** [danielnemenyi/mad-spinning-top#13]
https://mad-spinning-top.netlify.app/blog

Mentions "– writing in progress –" so assume there's more copy to come?

Also title reads 'Blog Spain' but is that the full title?

I might have missed the updated file!

**Comment by toupiefolle** [comment]
I don't think there is an updated one. 
I think it should be 'Blog Spin', could you correct this please. 

P

**Comment by danielnemenyi** [comment]
Title corrected: d95eeb2
