### ISSUE TITLE
Only show popups for people's names?

### ISSUE THREAD

**Issue by danielnemenyi** [danielnemenyi/mad-spinning-top#5]
Currently it's being launched for posts, but this does not seem very useful.

**Comment by toupiefolle** [comment]
I need to think about what this means.

**Comment by danielnemenyi** [comment]
I've made it so that only hovering (or tapping on a mobile) over a person's name brings up the backlink box, since we weren't linking blog posts to one another at least enough to make the backlink info  useful for them. Hopefully it should all feel more consistent now.
