### ISSUE TITLE
Pop-up box of heavily-referenced author is being vertically cropped

### ISSUE THREAD

**Issue by danielnemenyi** [danielnemenyi/mad-spinning-top#6]
**Describe the bug**
When you hover over the name of someone who is heavily referenced the pop-up box does not contain all their posts. 

**To reproduce**
1. Go to https://mad-spinning-top.netlify.app/notes/urbanism-bibliographical-notes-and-liane-moz%C3%A8re
2. Hover cursor over Michel Foucault or Felix Guattari
3. Box appears, but cropped. 

**Expected behavior**
Should display all posts, or perhaps a scroll bar? 

Perhaps the pop-up box should be replaced by a sidebar that sticks to the right of the page on web devices, and occupies the bottom half of the screen on mobiles?

**Screenshots**
![image](https://user-images.githubusercontent.com/8701448/170247671-13bbc155-e1fa-4ec8-9744-6a5a72e86d61.png)

**Desktop (please complete the following information):**
 - Operating system: [e.g. macOS 11.4]
 - Ruby version: [e.g. Ruby 2.7.1]

**Comment by toupiefolle** [comment]
There will be quite a few names with numerous mentions.

**Comment by danielnemenyi** [comment]
Box has now been moved to a sidebar on larger screens, and to a popup on smaller. This leaves more room, however maybe not enough, so we will have to keep testing as we add more posts.

Desktop:
![image](https://user-images.githubusercontent.com/8701448/172456173-c21ae4fe-2e34-4b3a-a3a1-cbe51062d145.png)

Mobile:
![image](https://user-images.githubusercontent.com/8701448/172456255-1981d58f-9f0d-45d5-8ba2-39fe088bd657.png)
